spring:
    data:
        mongodb:
            # uri : mongodb+srv://keyurteqheal:XivjDSa5YxFeslJN@democurd.k7qgf.mongodb.net/
            uri : mongodb+srv://keyurteqheal:XivjDSa5YxFeslJN@democurd.k7qgf.mongodb.net/User?retryWrites=true&w=majority&ssl=true
            database : User
server:
  port: 8081